language: generic
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install gawk util-linux realpath qemu-user-static git p7zip-full python3 -y

install:
  - cd $TRAVIS_BUILD_DIR && cd ..
  - git clone https://github.com/guysoft/CustomPiOS.git
  - cd OctoPi/src/image
  - wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspbian_lite_latest'

before_script:
  - cd $TRAVIS_BUILD_DIR/src
  - ../../CustomPiOS/src/update-custompios-paths
  - sudo modprobe loop

script:
  - sudo bash -x ./build_dist